INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('KIA','NIRO','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('HYUNDAI','KONA','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('JEEP','GRAND CHEROKEE','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TESLA','MODEL 3','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','I3','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('CHRYSLER','PACIFICA','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TESLA','MODEL Y','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FORD','FUSION','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TOYOTA','PRIUS PRIME','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('AUDI','E-TRON','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('NISSAN','LEAF','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','X5','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TESLA','MODEL S','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('CHEVROLET','VOLT','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TOYOTA','RAV4','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FIAT','500','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('CHEVROLET','BOLT EV','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('VOLKSWAGEN','ID.4','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','330E','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('AUDI','A3','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FORD','FOCUS','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('KIA','SORENTO','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('HYUNDAI','TUCSON','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TESLA','MODEL X','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('VOLVO','XC60','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('KIA','SOUL','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('KIA','SPORTAGE','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('MINI','HARDTOP','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('JEEP','WRANGLER','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('AUDI','Q5 E','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('SMART','EQ FORTWO','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','X3','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('RIVIAN','R1S','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('AUDI','Q5','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('HONDA','CLARITY','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FORD','F-150','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('VOLVO','XC90','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('PORSCHE','CAYENNE','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TOYOTA','RAV4 PRIME','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('CHEVROLET','SPARK','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('KIA','OPTIMA','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('RIVIAN','R1T','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FORD','ESCAPE','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('KIA','SOUL EV','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('MITSUBISHI','OUTLANDER','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TESLA','ROADSTER','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('SMART','FORTWO','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FORD','MUSTANG MACH-E','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','740E','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('KIA','EV6','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('SUBARU','SOLTERRA','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','IX','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('CHEVROLET','BOLT EUV','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('HYUNDAI','IONIQ 5','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','I4','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FORD','TRANSIT','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('HYUNDAI','KONA ELECTRIC','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('POLESTAR','PS2','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('MERCEDES-BENZ','EQB-CLASS','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('TOYOTA','PRIUS PLUG-IN','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('HYUNDAI','SANTA FE','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('PORSCHE','TAYCAN','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('CADILLAC','LYRIQ','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('MERCEDES-BENZ','EQS-CLASS SEDAN','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('JAGUAR','I-PACE','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','530E','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('BMW','I8','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('VOLVO','XC40','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('MINI','COUNTRYMAN','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('VOLVO','S60','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('CADILLAC','ELR','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('LINCOLN','AVIATOR','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('HYUNDAI','IONIQ','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('AUDI','E-TRON GT','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('GENESIS','G80','Battery Electric Vehicle (BEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('FORD','C-MAX','Plug-in Hybrid Electric Vehicle (PHEV)');
INSERT INTO modeldetails (`Make`,`Model`,`EVType`) VALUES ('VOLKSWAGEN','E-GOLF','Battery Electric Vehicle (BEV)');