INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (94901,'Marin','San Rafael','CA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98103,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98011,'King','Bothell','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98908,'Yakima','Yakima','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98034,'King','Kirkland','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98501,'Thurston','Olympia','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98271,'Snohomish','Marysville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98042,'King','Kent','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98072,'King','Woodinville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98239,'Island','Coupeville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98004,'King','Bellevue','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98033,'King','Kirkland','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98367,'Kitsap','Port Orchard','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98366,'Kitsap','Port Orchard','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98275,'Snohomish','Mukilteo','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98052,'King','Redmond','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98579,'Thurston','Rochester','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98112,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98125,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98311,'Kitsap','Bremerton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98370,'Kitsap','Poulsbo','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98312,'Kitsap','Bremerton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98108,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98258,'Snohomish','Lake Stevens','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98383,'Kitsap','Silverdale','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98346,'Kitsap','Kingston','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98506,'Thurston','Olympia','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98022,'King','Enumclaw','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98109,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98006,'King','Bellevue','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98133,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98002,'King','Auburn','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98936,'Yakima','Moxee','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98947,'Yakima','Tieton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98057,'King','Renton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98008,'King','Bellevue','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98188,'King','Tukwila','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98392,'Kitsap','Suquamish','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98277,'Island','Oak Harbor','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98177,'King','Shoreline','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98380,'Kitsap','Seabeck','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98075,'King','Sammamish','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98027,'King','Issaquah','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98272,'Snohomish','Monroe','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98110,'Kitsap','Bainbridge Island','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98597,'Thurston','Yelm','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98028,'King','Kenmore','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98502,'Thurston','Olympia','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98166,'King','Burien','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98168,'King','Tukwila','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98292,'Snohomish','Stanwood','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98223,'Snohomish','Arlington','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98038,'King','Maple Valley','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98116,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98039,'King','Medina','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98056,'King','Renton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98199,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98074,'King','Sammamish','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98021,'Snohomish','Bothell','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98023,'King','Federal Way','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98296,'Snohomish','Snohomish','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98119,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98948,'Yakima','Toppenish','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98144,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98204,'Snohomish','Everett','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98106,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98036,'Snohomish','Lynnwood','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98310,'Kitsap','Bremerton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98107,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98117,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98092,'King','Auburn','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98198,'King','Des Moines','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98503,'Thurston','Lacey','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98903,'Yakima','Yakima','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98146,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98105,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98902,'Yakima','Yakima','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98516,'Thurston','Lacey','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98513,'Thurston','Olympia','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98512,'Thurston','Tumwater','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98155,'King','Shoreline','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98115,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98020,'Snohomish','Edmonds','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98340,'Kitsap','Hansville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98178,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98104,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98026,'Snohomish','Edmonds','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98059,'King','Renton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98589,'Thurston','Tenino','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98118,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98225,'Whatcom','Bellingham','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98045,'King','North Bend','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98270,'Snohomish','Marysville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98374,'Pierce','Puyallup','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99163,'Whitman','Pullman','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98576,'Thurston','Rainier','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98273,'Skagit','Mount Vernon','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98053,'King','Redmond','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98922,'Kittitas','Cle Elum','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98327,'Pierce','Dupont','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98029,'King','Issaquah','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98233,'Skagit','Burlington','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98208,'Snohomish','Everett','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99204,'Spokane','Spokane','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98221,'Skagit','Anacortes','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98229,'Whatcom','Bellingham','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98257,'Skagit','La Conner','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99362,'Walla Walla','Walla Walla','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98019,'King','Duvall','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98249,'Island','Freeland','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98801,'Chelan','Wenatchee','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99205,'Spokane','Spokane','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98087,'Snohomish','Lynnwood','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98848,'Grant','Quincy','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98274,'Skagit','Mount Vernon','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98122,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98815,'Chelan','Cashmere','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98203,'Snohomish','Everett','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98290,'Snohomish','Snohomish','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98237,'Skagit','Concrete','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98851,'Grant','Soap Lake','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99203,'Spokane','Spokane','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98037,'Snohomish','Lynnwood','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98012,'Snohomish','Mill Creek','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98826,'Chelan','Leavenworth','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98837,'Grant','Moses Lake','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98024,'King','Snoqualmie','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99207,'Spokane','Spokane','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99115,'Grant','Coulee City','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98284,'Skagit','Sedro-Woolley','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98226,'Whatcom','Bellingham','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98032,'King','Kent','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98372,'Pierce','Puyallup','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98232,'Skagit','Bow','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98001,'King','Auburn','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98926,'Kittitas','Ellensburg','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98315,'Kitsap','Silverdale','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98136,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98236,'Island','Clinton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98005,'King','Bellevue','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98321,'Pierce','Buckley','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98282,'Island','Camano Island','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99167,'Stevens','Rice','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98362,'Clallam','Port Angeles','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99109,'Stevens','Chewelah','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98201,'Snohomish','Everett','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98043,'Snohomish','Mountlake Terrace','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98070,'King','Vashon','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98532,'Lewis','Chehalis','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98260,'Island','Langley','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98943,'Kittitas','South Cle Elum','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99357,'Grant','Royal City','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98823,'Grant','Ephrata','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98822,'Chelan','Entiat','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98014,'King','Carnation','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99223,'Spokane','Spokane','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98846,'Okanogan','Pateros','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98252,'Snohomish','Granite Falls','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99114,'Stevens','Colville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98664,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98121,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98844,'Okanogan','Oroville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98338,'Pierce','Graham','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98901,'Yakima','Yakima','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98858,'Douglas','Waterville','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98629,'Clark','La Center','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98498,'Pierce','Lakewood','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98102,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98682,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98606,'Clark','Brush Prairie','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98031,'King','Kent','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98368,'Jefferson','Port Townsend','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98662,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98685,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98686,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98674,'Cowlitz','Woodland','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98359,'Kitsap','Olalla','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98382,'Jefferson','Sequim','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98058,'King','Renton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98047,'King','Pacific','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98603,'Cowlitz','Ariel','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98632,'Cowlitz','Longview','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (99026,'Stevens','Nine Mile Falls','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98148,'King','Seatac','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98055,'King','Renton','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98007,'King','Bellevue','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98101,'King','Seattle','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98320,'Jefferson','Brinnon','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98625,'Cowlitz','Kalama','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98671,'Clark','Washougal','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98663,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98030,'King','Kent','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98607,'Clark','Camas','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98604,'Clark','Battle Ground','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98684,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98660,'Clark','Vancouver','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98365,'Jefferson','Port Ludlow','WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98942,'Yakima', 'Selah', 'WA');
INSERT INTO location (`PostalCode`,`County`,`City`,`State`) VALUES (98683,'Clark', 'Vancouver', 'WA');